In [1]:
import pandas
import eland
import os
from elasticsearch import Elasticsearch

In [14]:
df = pandas.read_csv(
    'ripa_stops_datasd.csv',
    keep_default_na=False,
    parse_dates=["date_stop"],
)

In [15]:
df.head()

,stop_id,ori,agency,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,assignment,...,beat_name,pid,isstudent,perceived_limited_english,perceived_age,perceived_gender,gender_nonconforming,gend,gend_nc,perceived_lgbt
0,2443,CA0371100,SD,10,2018-07-01,00:01:37,30,0,1,"Patrol, traffic enforcement, field operations",...,Pacific Beach 122,1,0,0,25,Male,0,1,,No
1,2444,CA0371100,SD,18,2018-07-01,00:03:34,10,0,1,"Patrol, traffic enforcement, field operations",...,Mission Beach 121,1,0,0,25,Male,0,1,,No
2,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,El Cerrito 822,1,0,0,30,Male,0,1,,No
3,2447,CA0371100,SD,1,2018-07-01,00:05:43,15,1,10,Other,...,El Cerrito 822,2,0,0,30,Female,0,2,,No
4,2448,CA0371100,SD,3,2018-07-01,00:19:06,5,0,1,"Patrol, traffic enforcement, field operations",...,Ocean Beach 614,1,0,0,23,Male,0,1,,No

In [16]:
# Problem Beat name Different than Beat
pandas.unique(df['beat_name'])

array(['Pacific Beach 122', 'Mission Beach 121', 'El Cerrito 822',
       'Ocean Beach 614', 'University City 115', 'Lincoln Park 446',
       'Colina Del Sol 826', 'Balboa Park 531', 'La Jolla 124',
       'Gaslamp 523', 'Carmel Mountain 232', 'Castle 834',
       'Mountain View 441', 'Otay Mesa 713', 'North Clairemont 114',
       'Lake Murray 324', 'Otay Mesa West 723', 'Horton Plaza 525',
       'Nestor 722', 'Marina 522', 'Fairmount Village 833', 'Midtown 628',
       'Sorrento Valley 931', 'Mission Valley West 623',
       'Linda Vista 621', 'Golden Hill 517', 'Talmadge 824',
       'Corridor 838', 'Barrio Logan 511', 'Clairemont Mesa East 111',
       'Carmel Valley 934', 'Logan Heights 512', 'Core-Columbia 524',
       'Hillcrest 627', 'Mira Mesa 242', 'North Park 813',
       'Cherokee Point 839', 'Kearney Mesa 313', 'Normal Heights 811',
       'Palm City 724', 'San Ysidro 712', 'Midway District 611',
       'College East 327', 'Bay Park 116', 'East Village 521',
       'Serra Mesa 311', 'Mission Bay Park 123', 'Sabre Springs 231',
       'Valencia Park 432', 'Swan Canyon 836', 'Grantville 321',
       'Oak Park 451', 'Loma Portal 612', 'Sunset Cliffs 618',
       'Torrey Pines 126', 'Azalea/Hollywood Park 835', 'Unknown 999',
       'College West 326', 'Fairmount Park 837', 'Point Loma Heights 613',
       'Teralta West 832', 'Miramar 243', 'Del Cerro 323',
       'Rancho Bernardo 234', 'University Heights 624',
       'Rolando Park 841', 'Rolando 821', 'Egger Highlands 721',
       'Teralta East 831', 'Border 714', 'Mission Valley East 315',
       'Sherman Heights 514', 'Old Town 625', 'Mission Hills 626',
       'Bay Terraces 437', 'San Carlos 325', "O'Farrell 452",
       'Tierra Santa 312', 'Petco Park 541', 'Kensington 825',
       'Chollas View 445', 'Morena 622', 'Grant Hill 515', 'Cortez 526',
       'Ocean Crest 725', 'Bay Ho 113', 'Allied Gardens 322',
       'Little Italy 528', 'Del Mar Heights 933', 'Jamacha/Lomita 434',
       'Ridgeview/Webster 447', 'Emerald Hills 431', 'Scripps Ranch 241',
       'Miramar Ranch North 246', 'Clairemont Mesa West 112',
       'Shelltown 443', 'Stockton 516', 'Park West 529', 'Alta Vista 439',
       'Rancho Penasquitos 233', 'Roseville/Fleet Ridge 615',
       'Torrey Highlands 936', 'Mt. Hope 444', 'North City 935',
       'Paradise Hills 438', 'Birdland 314', 'San Pasqual 235',
       'Skyline 436', 'Redwood Village 823', 'Black Mountain Ranch 937',
       'Chollas Creek 827', 'Southcrest 442', 'Tijuana River Valley 711',
       'La Jolla Village 125', 'Wooded Area 617', 'Adams North 814',
       'South Park 518', 'Qualcomm 316', 'Encanto 433', 'Fox Canyon 828',
       'Harborview 527', 'Rancho Encantada 245', 'Burlingame 812',
       'Torrey Preserve 932', 'Broadway Heights 435', 'Islenair 829',
       'OUT OF COUNTY 999'], dtype=object)

In [17]:
# Solution 1
df[['beat_name', 'beat']] = df['beat_name'].str.rsplit(' ', 1, expand=True)

In [21]:
df.tail()

,stop_id,ori,agency,exp_years,date_stop,time_stop,stopduration,stop_in_response_to_cfs,officer_assignment_key,assignment,...,beat_name,pid,isstudent,perceived_limited_english,perceived_age,perceived_gender,gender_nonconforming,gend,gend_nc,perceived_lgbt
427360,387885,CA0371100,SD,1,2020-12-31,23:30:00,40,0,1,"Patrol, traffic enforcement, field operations",...,Sorrento Valley,1,0,0,25,Male,0,1,,No
427361,387893,CA0371100,SD,1,2020-12-31,22:17:00,180,1,1,"Patrol, traffic enforcement, field operations",...,Talmadge,1,0,0,60,Male,0,1,,No
427362,387910,CA0371100,SD,1,2020-12-31,12:51:19,40,1,1,"Patrol, traffic enforcement, field operations",...,Bay Park,1,0,0,30,Male,0,1,,No
427363,387910,CA0371100,SD,1,2020-12-31,12:51:19,40,1,1,"Patrol, traffic enforcement, field operations",...,Bay Park,2,0,0,30,Female,0,2,,No
427364,387978,CA0371100,SD,1,2020-12-31,14:00:00,10,0,1,"Patrol, traffic enforcement, field operations",...,North Park,1,0,0,55,Female,0,2,,No

In [19]:
# Upload to Elastic Cloud

client = Elasticsearch(
    cloud_id=os.environ.get('CLOUD_ID'),
    http_auth=(os.environ.get('ES_CLIENT_USERNAME'),
         os.environ.get('ES_CLIENT_PASSWORD')
         )
)

In [20]:
ed = eland.pandas_to_eland(
                df,
                es_client=client,
                es_dest_index="sd-ripa-basic-stop",
                es_if_exists="replace",
                es_refresh=True,
            )